import os
from datetime import datetime

from Programma_CS2_RENAN.backend.processing.state_reconstructor import RAPStateReconstructor
from Programma_CS2_RENAN.ingestion.demo_loader import DemoLoader
from Programma_CS2_RENAN.observability.logger_setup import get_logger
from Programma_CS2_RENAN.reporting.visualizer import MatchVisualizer

_logger = get_logger("cs2analyzer.report_generator")


class MatchReportGenerator:
    def __init__(self, db_manager):
        self.db = db_manager
        self.viz = MatchVisualizer()
        self.output_dir = "reports"
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_report(self, demo_path):
        """
        Full pipeline: Parse -> Analyze -> Visualize -> Report.
        """
        # 1. Parse Demo
        loader = DemoLoader()
        parse_result = loader.load_demo(demo_path)
        # Result is Dict[map_name, Tuple[frames, events, segments]]
        map_name = list(parse_result.keys())[0] if parse_result else "unknown"
        if map_name == "unknown":
            _logger.warning("Cannot generate report: map_name is 'unknown' for demo %s", demo_path)
            return None

        frames, events, _ = parse_result[map_name]

        # 2. Extract Data
        player_positions = []
        deaths = []

        for frame in frames:
            for p in frame.players:
                # Assuming single player focus for now or filtering by user name needed in future
                # Taking all players for heatmap context currently
                player_positions.append((p.pos_x, p.pos_y))
                if p.health == 0:
                    deaths.append({"x": p.pos_x, "y": p.pos_y})

        # 3. Generate Visuals
        heatmap_path = self.viz.generate_heatmap(player_positions, map_name)

        # 4. Generate Text Report
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_filename = f"MatchReport_{map_name}_{timestamp}.md"
        report_path = os.path.join(self.output_dir, report_filename)

        with open(report_path, "w") as f:
            f.write(f"# CS2 Coach Match Report\n")
            f.write(f"**Map**: {map_name}\n")
            f.write(f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")

            f.write("## 1. Positioning Heatmap\n")
            f.write("This map shows your primary areas of operation.\n")
            f.write(f"![Heatmap]({os.path.abspath(heatmap_path)})\n\n")

            f.write("## 2. Fundamental Errors\n")
            f.write("- Analysis of deaths shows clustering at X, Y.\n")
            f.write("- Recommendation: Check 'Fundamentals' for hold angles in these zones.\n")

            f.write("\n> Generated by Macena CS2 Analyzer")

        return report_path
