import torch

from Programma_CS2_RENAN.backend.processing.feature_engineering.vectorizer import (
    METADATA_DIM,
    FeatureExtractor,
)
from Programma_CS2_RENAN.backend.processing.tensor_factory import (
    TensorConfig,
    TensorFactory,
    get_tensor_factory,
)
from Programma_CS2_RENAN.backend.storage.db_models import PlayerTickState
from Programma_CS2_RENAN.observability.logger_setup import get_logger

_logger = get_logger("cs2analyzer.state_reconstructor")


class RAPStateReconstructor:
    """
    State Reconstruction Engine (Entity Lifecycle & POMDP artifacts).
    Converts database tick records into tensors for RAP-Coach.

    Uses the unified FeatureExtractor to ensure training/inference feature parity.
    Vision tensors are now generated by TensorFactory (Phase 1: Vision Bridge).

    IMPORTANT — Player-POV mode vs Legacy mode:
      Pass `knowledge` (a PlayerKnowledge object) to `reconstruct_belief_tensors()`
      to activate Player-POV mode. Without it, the method falls back to legacy mode
      (full information, no player perspective). Training with legacy mode while
      GhostEngine uses Player-POV at inference causes training/inference skew.
    """

    def __init__(
        self,
        sequence_length: int = 32,
        map_name: str = "de_mirage",
        require_pov: bool = False,
        tensor_config: TensorConfig | None = None,
    ):
        self.sequence_length = sequence_length
        self.metadata_dim = METADATA_DIM  # Use unified constant
        self.map_name = map_name
        self.require_pov = require_pov
        # P-SR-02: Accept explicit tensor config to avoid training/inference skew.
        if tensor_config is not None:
            self.tensor_factory = TensorFactory(config=tensor_config)
        else:
            self.tensor_factory = get_tensor_factory()

    def reconstruct_belief_tensors(self, ticks: list[PlayerTickState], knowledge=None):
        """
        Translates a sequence of ticks into Perception and Metadata tensors.

        Args:
            ticks:     Sequence of PlayerTickState records from the DB.
            knowledge: Optional PlayerKnowledge for Player-POV mode.
                       When None, legacy (full-information) mode is used.
                       NOTE: If GhostEngine uses POV mode at inference, training
                       MUST also pass knowledge here to avoid training/inference skew.

        Vision Bridge Implementation (Phase 1):
        - Map tensor: Top-down tactical view (enemy/teammate positions)
        - View tensor: FOV approximation (what player can see)
        - Motion tensor: Velocity/movement encoding

        Raises:
            ValueError: If require_pov=True and knowledge is None (R4-04-01).
        """
        if knowledge is None:
            if self.require_pov:
                raise ValueError(
                    "R4-04-01: knowledge=None but require_pov=True. Training with "
                    "legacy mode while GhostEngine uses Player-POV causes skew."
                )
            _logger.warning(
                "reconstruct_belief_tensors: knowledge=None — running in LEGACY (full-info) mode. "
                "If GhostEngine uses Player-POV at inference, pass a PlayerKnowledge object here "
                "to prevent training/inference skew."
            )

        # C-01: Build explicit context dicts from enriched PlayerTickState fields.
        # This ensures features 20-24 are populated during training, matching
        # the inference path in ghost_engine.py which builds context from DemoFrame.
        contexts = [
            {
                "time_in_round": getattr(t, "time_in_round", 0.0),
                "bomb_planted": getattr(t, "bomb_planted", False),
                "teammates_alive": getattr(t, "teammates_alive", 0),
                "enemies_alive": getattr(t, "enemies_alive", 0),
                "team_economy": getattr(t, "team_economy", 0),
            }
            for t in ticks
        ]

        # Use UNIFIED FeatureExtractor for metadata (Critical for consistency)
        metadata = FeatureExtractor.extract_batch(
            ticks, map_name=self.map_name, contexts=contexts
        )
        # P-SR-01: Validate feature parity at training boundary
        FeatureExtractor.validate_feature_parity(metadata, label="training")
        metadata_tensor = torch.tensor(metadata, dtype=torch.float32).unsqueeze(0)

        # Generate real Perception Tensors via TensorFactory (Vision Bridge)
        vision_tensors = self.tensor_factory.generate_all_tensors(
            ticks, self.map_name, knowledge=knowledge
        )

        # Add batch dimension
        view_frame = vision_tensors["view"].unsqueeze(0)
        map_frame = vision_tensors["map"].unsqueeze(0)
        motion_diff = vision_tensors["motion"].unsqueeze(0)

        return {
            "view": view_frame,
            "map": map_frame,
            "motion": motion_diff,
            "metadata": metadata_tensor,
        }

    def segment_match_into_windows(self, match_ticks: list[PlayerTickState]):
        """
        Applies temporal windowing with 50% overlap (Layer 2 Temporal Perception).

        The step is sequence_length // 2 (50% overlap). The last window is included
        only if it has a full sequence_length worth of ticks. Trailing ticks that
        would form a shorter window are intentionally omitted (≤ sequence_length//2 ticks lost).
        """
        windows = []
        step = self.sequence_length // 2
        for i in range(0, len(match_ticks) - self.sequence_length + 1, step):
            windows.append(match_ticks[i : i + self.sequence_length])
        return windows
