"""add_nullable_heartbeat_to_coachstate

Revision ID: 57a72f0df21e
Revises: e3013f662fd4
Create Date: 2026-01-12 23:42:14.874633

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57a72f0df21e"
down_revision: Union[str, Sequence[str], None] = "e3013f662fd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coachstate", sa.Column("last_heartbeat", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coachstate", "last_heartbeat")
    # ### end Alembic commands ###
