"""Add_Pro_Stats

Revision ID: 89850b6e0a49
Revises: 7a30a0ea024e
Create Date: 2026-01-11 15:56:10.926238

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89850b6e0a49"
down_revision: Union[str, Sequence[str], None] = "7a30a0ea024e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proteam",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hltv_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("world_rank", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proteam_hltv_id"), "proteam", ["hltv_id"], unique=True)
    op.create_index(op.f("ix_proteam_name"), "proteam", ["name"], unique=False)
    op.create_table(
        "proplayer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hltv_id", sa.Integer(), nullable=False),
        sa.Column("nickname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("real_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["proteam.hltv_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proplayer_hltv_id"), "proplayer", ["hltv_id"], unique=True)
    op.create_index(op.f("ix_proplayer_nickname"), "proplayer", ["nickname"], unique=False)
    op.create_table(
        "proplayerstatcard",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("rating_2_0", sa.Float(), nullable=False),
        sa.Column("dpr", sa.Float(), nullable=False),
        sa.Column("kast", sa.Float(), nullable=False),
        sa.Column("impact", sa.Float(), nullable=False),
        sa.Column("adr", sa.Float(), nullable=False),
        sa.Column("kpr", sa.Float(), nullable=False),
        sa.Column("detailed_stats_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("time_span", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["proplayer.hltv_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proplayerstatcard_player_id"), "proplayerstatcard", ["player_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proplayerstatcard_player_id"), table_name="proplayerstatcard")
    op.drop_table("proplayerstatcard")
    op.drop_index(op.f("ix_proplayer_nickname"), table_name="proplayer")
    op.drop_index(op.f("ix_proplayer_hltv_id"), table_name="proplayer")
    op.drop_table("proplayer")
    op.drop_index(op.f("ix_proteam_name"), table_name="proteam")
    op.drop_index(op.f("ix_proteam_hltv_id"), table_name="proteam")
    op.drop_table("proteam")
    # ### end Alembic commands ###
