"""Link_Pro_Physics_To_Stats

Revision ID: 8a93567a2798
Revises: 89850b6e0a49
Create Date: 2026-01-11 16:13:47.900392

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a93567a2798"
down_revision: Union[str, Sequence[str], None] = "89850b6e0a49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("playermatchstats", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pro_player_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_playermatchstats_pro_player_id"), ["pro_player_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_pro_player_stats", "proplayer", ["pro_player_id"], ["hltv_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("playermatchstats", schema=None) as batch_op:
        batch_op.drop_constraint("fk_pro_player_stats", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_playermatchstats_pro_player_id"))
        batch_op.drop_column("pro_player_id")
    # ### end Alembic commands ###
