"""add_service_notification_table

Revision ID: da7a6be5c0c7
Revises: 57a72f0df21e
Create Date: 2026-01-12 23:46:40.189357

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da7a6be5c0c7"
down_revision: Union[str, Sequence[str], None] = "57a72f0df21e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servicenotification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("daemon", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("severity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_servicenotification_daemon"), "servicenotification", ["daemon"], unique=False
    )
    op.create_index(
        op.f("ix_servicenotification_is_read"), "servicenotification", ["is_read"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_servicenotification_is_read"), table_name="servicenotification")
    op.drop_index(op.f("ix_servicenotification_daemon"), table_name="servicenotification")
    op.drop_table("servicenotification")
    # ### end Alembic commands ###
