"""Add_missing_profile_fields

Revision ID: f769fbe67229
Revises:
Create Date: 2025-12-26 07:06:24.142790

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f769fbe67229"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestiontask",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("demo_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_pro", sa.Boolean(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestiontask_demo_path"), "ingestiontask", ["demo_path"], unique=False
    )
    op.create_index(op.f("ix_ingestiontask_status"), "ingestiontask", ["status"], unique=False)
    op.add_column(
        "playerprofile",
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    )
    op.add_column(
        "playerprofile",
        sa.Column("profile_pic_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "playerprofile", sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "playerprofile",
        sa.Column("social_links_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "playerprofile",
        sa.Column("pc_specs_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "playerprofile",
        sa.Column("graphic_settings_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "playerprofile",
        sa.Column("cfg_file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "playerprofile",
        sa.Column("steam_avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playerprofile", "steam_avatar_url")
    op.drop_column("playerprofile", "cfg_file_path")
    op.drop_column("playerprofile", "graphic_settings_json")
    op.drop_column("playerprofile", "pc_specs_json")
    op.drop_column("playerprofile", "social_links_json")
    op.drop_column("playerprofile", "role")
    op.drop_column("playerprofile", "profile_pic_path")
    op.drop_column("playerprofile", "bio")
    op.drop_index(op.f("ix_ingestiontask_status"), table_name="ingestiontask")
    op.drop_index(op.f("ix_ingestiontask_demo_path"), table_name="ingestiontask")
    op.drop_table("ingestiontask")
    # ### end Alembic commands ###
