"""baseline_schema

Revision ID: b609a11e13cc
Revises:
Create Date: 2026-01-22 22:00:59.608382

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # Fix: Added missing import

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b609a11e13cc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matchresult",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("team_a_id", sa.Integer(), nullable=True),
        sa.Column("team_b_id", sa.Integer(), nullable=True),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("event_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("map_picks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.create_index(op.f("ix_matchresult_event_name"), "matchresult", ["event_name"], unique=False)
    op.create_table(
        "mapveto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("map_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matchresult.match_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mapveto_match_id"), "mapveto", ["match_id"], unique=False)
    op.drop_table("ingestiontask_archive")
    op.alter_column(
        "coachstate",
        "current_epoch",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "coachstate",
        "total_epochs",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "coachstate",
        "train_loss",
        existing_type=sa.FLOAT(),
        nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "val_loss",
        existing_type=sa.FLOAT(),
        nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "eta_seconds",
        existing_type=sa.FLOAT(),
        nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "system_load_cpu",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "system_load_mem",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "parsing_progress",
        existing_type=sa.FLOAT(),
        nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "total_matches_processed",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "coachstate",
        "cpu_limit",
        existing_type=sa.FLOAT(),
        nullable=False,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column(
        "coachstate",
        "ram_limit",
        existing_type=sa.FLOAT(),
        nullable=False,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column(
        "coachstate",
        "gpu_limit",
        existing_type=sa.FLOAT(),
        nullable=False,
        existing_server_default=sa.text("(0.5)"),
    )
    op.add_column(
        "playertickstate",
        sa.Column("demo_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(
        op.f("ix_playertickstate_demo_name"), "playertickstate", ["demo_name"], unique=False
    )
    op.add_column("proplayerstatcard", sa.Column("headshot_pct", sa.Float(), nullable=False))
    op.add_column("proplayerstatcard", sa.Column("maps_played", sa.Integer(), nullable=False))
    op.add_column("proplayerstatcard", sa.Column("opening_kill_ratio", sa.Float(), nullable=False))
    op.add_column(
        "proplayerstatcard", sa.Column("opening_duel_win_pct", sa.Float(), nullable=False)
    )
    op.add_column("proplayerstatcard", sa.Column("clutch_win_count", sa.Integer(), nullable=False))
    op.add_column("proplayerstatcard", sa.Column("multikill_round_pct", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proplayerstatcard", "multikill_round_pct")
    op.drop_column("proplayerstatcard", "clutch_win_count")
    op.drop_column("proplayerstatcard", "opening_duel_win_pct")
    op.drop_column("proplayerstatcard", "opening_kill_ratio")
    op.drop_column("proplayerstatcard", "maps_played")
    op.drop_column("proplayerstatcard", "headshot_pct")
    op.drop_index(op.f("ix_playertickstate_demo_name"), table_name="playertickstate")
    op.drop_column("playertickstate", "demo_name")
    op.alter_column(
        "coachstate",
        "gpu_limit",
        existing_type=sa.FLOAT(),
        nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column(
        "coachstate",
        "ram_limit",
        existing_type=sa.FLOAT(),
        nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column(
        "coachstate",
        "cpu_limit",
        existing_type=sa.FLOAT(),
        nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column(
        "coachstate",
        "total_matches_processed",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "coachstate",
        "parsing_progress",
        existing_type=sa.FLOAT(),
        nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "system_load_mem",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "system_load_cpu",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "eta_seconds",
        existing_type=sa.FLOAT(),
        nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "val_loss",
        existing_type=sa.FLOAT(),
        nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "train_loss",
        existing_type=sa.FLOAT(),
        nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "coachstate",
        "total_epochs",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "coachstate",
        "current_epoch",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.create_table(
        "ingestiontask_archive",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("demo_path", sa.TEXT(), nullable=True),
        sa.Column("is_pro", sa.NUMERIC(), nullable=True),
        sa.Column("status", sa.TEXT(), nullable=True),
        sa.Column("retry_count", sa.INTEGER(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.NUMERIC(), nullable=True),
        sa.Column("updated_at", sa.NUMERIC(), nullable=True),
        sa.Column("last_tick_processed", sa.INTEGER(), nullable=True),
    )
    op.drop_index(op.f("ix_mapveto_match_id"), table_name="mapveto")
    op.drop_table("mapveto")
    op.drop_index(op.f("ix_matchresult_event_name"), table_name="matchresult")
    op.drop_table("matchresult")
    # ### end Alembic commands ###
