// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/heatmap": {
            "post": {
                "description": "Returns the heatmap image (PNG) for a match based on the provided MatchId and MatchDescription.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Heatmap"
                ],
                "summary": "Get heatmap image for a match",
                "parameters": [
                    {
                        "description": "Payload with MatchId and MatchDescription",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/heatmapmatch.MapData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Heatmap image URL",
                        "schema": {
                            "$ref": "#/definitions/models.HeatmapResponse"
                        }
                    },
                    "400": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/last-results": {
            "post": {
                "description": "Returns all available results on /results from hltv",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Results"
                ],
                "summary": "Last available matches result",
                "responses": {
                    "200": {
                        "description": "List of live matches",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Results"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/live-now": {
            "get": {
                "description": "Return all matches playing now",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Matches live now",
                "responses": {
                    "200": {
                        "description": "List of live matches",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Match"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/match": {
            "post": {
                "description": "Using the match ID obtained from /api/last-results, this endpoint returns detailed information about a single match, including maps, results, and team stats.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "Get information for a single match",
                "parameters": [
                    {
                        "description": "Request payload containing the day or other filters",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/match.Match"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of past match results with map links",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/match.LastMatchSummary"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/match-stats": {
            "post": {
                "description": "Using the map ID and description obtained from /match, this endpoint returns detailed statistics for that specific map.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "Get stats for a single map from a match",
                "parameters": [
                    {
                        "description": "Request payload containing the day or other filters",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mapstats.MapData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of past match results with map links",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mapstats.MatchStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/matches:day": {
            "get": {
                "description": "Returns all nextMatches within HLTV window context (current day + 5 days). Send only the day as a query parameter. Example: if you want matches for December 16 while in December, send only \"16\".",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Matches"
                ],
                "summary": "Scheduled matches",
                "responses": {
                    "200": {
                        "description": "List of live matches",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Match"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "heatmapmatch.MapData": {
            "type": "object",
            "properties": {
                "matchDescription": {
                    "type": "string"
                },
                "matchid": {
                    "type": "string"
                }
            }
        },
        "mapstats.MapData": {
            "type": "object",
            "properties": {
                "matchDescription": {
                    "type": "string"
                },
                "matchid": {
                    "type": "string"
                }
            }
        },
        "mapstats.MatchStats": {
            "type": "object",
            "properties": {
                "StatsTeam1": {
                    "$ref": "#/definitions/models.TeamStats"
                },
                "StatsTeam2": {
                    "$ref": "#/definitions/models.TeamStats"
                }
            }
        },
        "match.LastMatchSummary": {
            "type": "object",
            "properties": {
                "mapVetoes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MapVeto"
                    }
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MapResult"
                    }
                },
                "teamStats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TeamStats"
                    }
                }
            }
        },
        "match.Match": {
            "type": "object",
            "properties": {
                "matchDescription": {
                    "type": "string"
                },
                "matchid": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Error with details"
                }
            }
        },
        "models.HeatmapResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://i.ibb.co/HpPSJt8s/Screenshot-from-2025-12-14-20-58-53.png"
                }
            }
        },
        "models.MapResult": {
            "type": "object",
            "properties": {
                "mapName": {
                    "type": "string"
                },
                "team1": {
                    "$ref": "#/definitions/models.TeamResult"
                },
                "team2": {
                    "$ref": "#/definitions/models.TeamResult"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.MapVeto": {
            "type": "object",
            "properties": {
                "mapName": {
                    "type": "string"
                },
                "teamChoice": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                }
            }
        },
        "models.Match": {
            "type": "object",
            "properties": {
                "bo": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "isLive": {
                    "type": "boolean"
                },
                "matchID": {
                    "type": "string"
                },
                "matchURL": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "teamA": {
                    "type": "string"
                },
                "teamB": {
                    "type": "string"
                }
            }
        },
        "models.Player": {
            "type": "object",
            "properties": {
                "adr": {
                    "type": "number",
                    "format": "float64"
                },
                "kast": {
                    "type": "number",
                    "format": "float64"
                },
                "kd": {
                    "type": "string"
                },
                "playerName": {
                    "type": "string"
                },
                "rating30": {
                    "type": "number",
                    "format": "float64"
                },
                "swing": {
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "models.Results": {
            "type": "object",
            "properties": {
                "bo": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "matchUrl": {
                    "type": "string"
                },
                "team1": {
                    "$ref": "#/definitions/models.Team"
                },
                "team2": {
                    "$ref": "#/definitions/models.Team"
                }
            }
        },
        "models.Team": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "wonMaps": {
                    "type": "integer"
                }
            }
        },
        "models.TeamResult": {
            "type": "object",
            "properties": {
                "teamName": {
                    "type": "string"
                },
                "wonMaps": {
                    "type": "integer"
                }
            }
        },
        "models.TeamStats": {
            "type": "object",
            "properties": {
                "playersStats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Player"
                    }
                },
                "teamName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
