definitions:
  heatmapmatch.MapData:
    properties:
      matchDescription:
        type: string
      matchid:
        type: string
    type: object
  mapstats.MapData:
    properties:
      matchDescription:
        type: string
      matchid:
        type: string
    type: object
  mapstats.MatchStats:
    properties:
      StatsTeam1:
        $ref: '#/definitions/models.TeamStats'
      StatsTeam2:
        $ref: '#/definitions/models.TeamStats'
    type: object
  match.LastMatchSummary:
    properties:
      mapVetoes:
        items:
          $ref: '#/definitions/models.MapVeto'
        type: array
      results:
        items:
          $ref: '#/definitions/models.MapResult'
        type: array
      teamStats:
        items:
          $ref: '#/definitions/models.TeamStats'
        type: array
    type: object
  match.Match:
    properties:
      matchDescription:
        type: string
      matchid:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      message:
        example: Error with details
        type: string
    type: object
  models.HeatmapResponse:
    properties:
      url:
        example: https://i.ibb.co/HpPSJt8s/Screenshot-from-2025-12-14-20-58-53.png
        type: string
    type: object
  models.MapResult:
    properties:
      mapName:
        type: string
      team1:
        $ref: '#/definitions/models.TeamResult'
      team2:
        $ref: '#/definitions/models.TeamResult'
      url:
        type: string
    type: object
  models.MapVeto:
    properties:
      mapName:
        type: string
      teamChoice:
        type: string
      teamName:
        type: string
    type: object
  models.Match:
    properties:
      bo:
        type: string
      event:
        type: string
      isLive:
        type: boolean
      matchID:
        type: string
      matchURL:
        type: string
      stage:
        type: string
      teamA:
        type: string
      teamB:
        type: string
    type: object
  models.Player:
    properties:
      adr:
        format: float64
        type: number
      kast:
        format: float64
        type: number
      kd:
        type: string
      playerName:
        type: string
      rating30:
        format: float64
        type: number
      swing:
        format: float64
        type: number
    type: object
  models.Results:
    properties:
      bo:
        type: string
      date:
        type: string
      event:
        type: string
      matchUrl:
        type: string
      team1:
        $ref: '#/definitions/models.Team'
      team2:
        $ref: '#/definitions/models.Team'
    type: object
  models.Team:
    properties:
      name:
        type: string
      wonMaps:
        type: integer
    type: object
  models.TeamResult:
    properties:
      teamName:
        type: string
      wonMaps:
        type: integer
    type: object
  models.TeamStats:
    properties:
      playersStats:
        items:
          $ref: '#/definitions/models.Player'
        type: array
      teamName:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/heatmap:
    post:
      consumes:
      - application/json
      description: Returns the heatmap image (PNG) for a match based on the provided
        MatchId and MatchDescription.
      parameters:
      - description: Payload with MatchId and MatchDescription
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/heatmapmatch.MapData'
      produces:
      - application/json
      responses:
        "200":
          description: Heatmap image URL
          schema:
            $ref: '#/definitions/models.HeatmapResponse'
        "400":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get heatmap image for a match
      tags:
      - Heatmap
  /api/last-results:
    post:
      description: Returns all available results on /results from hltv
      produces:
      - application/json
      responses:
        "200":
          description: List of live matches
          schema:
            items:
              $ref: '#/definitions/models.Results'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Last available matches result
      tags:
      - Results
  /api/live-now:
    get:
      description: Return all matches playing now
      produces:
      - application/json
      responses:
        "200":
          description: List of live matches
          schema:
            items:
              $ref: '#/definitions/models.Match'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Matches live now
      tags:
      - Matches
  /api/match:
    post:
      consumes:
      - application/json
      description: Using the match ID obtained from /api/last-results, this endpoint
        returns detailed information about a single match, including maps, results,
        and team stats.
      parameters:
      - description: Request payload containing the day or other filters
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/match.Match'
      produces:
      - application/json
      responses:
        "200":
          description: List of past match results with map links
          schema:
            items:
              $ref: '#/definitions/match.LastMatchSummary'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get information for a single match
      tags:
      - Match
  /api/match-stats:
    post:
      consumes:
      - application/json
      description: Using the map ID and description obtained from /match, this endpoint
        returns detailed statistics for that specific map.
      parameters:
      - description: Request payload containing the day or other filters
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/mapstats.MapData'
      produces:
      - application/json
      responses:
        "200":
          description: List of past match results with map links
          schema:
            items:
              $ref: '#/definitions/mapstats.MatchStats'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get stats for a single map from a match
      tags:
      - Match
  /api/matches:day:
    get:
      description: 'Returns all nextMatches within HLTV window context (current day
        + 5 days). Send only the day as a query parameter. Example: if you want matches
        for December 16 while in December, send only "16".'
      produces:
      - application/json
      responses:
        "200":
          description: List of live matches
          schema:
            items:
              $ref: '#/definitions/models.Match'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Scheduled matches
      tags:
      - Matches
swagger: "2.0"
